# Some Data Science

In this notebook I would like to do some basic data science on the dataset and see what is going on with regards to the task and data distribution.

In [2]:
dataset_url = 'https://figshare.com/ndownloader/files/35249488'

In [3]:
import numpy
import seaborn as sns
import pandas
import plotly_express as px
import plotly.graph_objects as go

In [4]:
%%time

# - getting the dataset
df = pandas.read_csv(dataset_url).drop(columns=['Unnamed: 0'])

CPU times: user 381 ms, sys: 68.3 ms, total: 450 ms
Wall time: 6.84 s


In [5]:
df.head()

VL         CD4    Rel CD4  Gender  Ethnic  Base Drug Combo  \
0  1141.895800  1070.03560  32.654160     1.0     4.0              0.0   
1   134.190550   444.54190  14.775723     1.0     4.0              0.0   
2    47.274055   230.53404  15.087534     1.0     4.0              0.0   
3   120.055940   419.28403  26.615877     1.0     4.0              1.0   
4    27.249084   230.72127  13.609289     1.0     4.0              1.0   

   Comp. INI  Comp. NNRTI  Extra PI  Extra pk-En  VL (M)  CD4 (M)  Drug (M)  \
0        3.0          1.0       5.0          0.0     1.0      1.0       0.0   
1        3.0          3.0       5.0          0.0     1.0      1.0       1.0   
2        3.0          3.0       5.0          0.0     0.0      0.0       1.0   
3        3.0          3.0       5.0          0.0     1.0      1.0       1.0   
4        3.0          3.0       5.0          0.0     1.0      1.0       1.0   

   PatientID  Timepoints  
0          0           0  
1          0           1  
2          0           2  
3          0           3  
4          0           4

In [6]:
print(f"""
    Statistics
    ============
      # of patients: {len(df.PatientID.unique())}
""")


    Statistics
      # of patients: 8916



In [7]:
df.groupby(['Gender']).count().loc[:, ['VL']].rename({'VL': 'record_count'}, axis=1)

record_count
Gender              
1.0           532380
2.0             2580

## Q: How are the records distributed w.r.t $\texttt{Gender}$ and $\texttt{Ethnic}$?

In what follows it can be seen that the distribution is not uniform, thus, it has to be taken into account in splitting data, balanced sampling if needed, and so on.

It should be noted that concepts related to fairness in reasoning and inference matter in problems as such.

In [8]:
df.groupby(['Ethnic']).count().loc[:, ['VL']].rename({'VL': 'record_count'}, axis=1)

record_count
Ethnic              
2.0              540
3.0           156360
4.0           378060

In [9]:
df.groupby(['Gender', 'Ethnic']).count().loc[:, ['VL']].rename({'VL': 'record_count'}, axis=1)

record_count
Gender Ethnic              
1.0    2.0              420
       3.0           156180
       4.0           375780
2.0    2.0              120
       3.0              180
       4.0             2280

## Q: What is the distribution of record length (number of elements) per patient?

In [10]:
df.groupby('PatientID').max().loc[:, ['Timepoints']]

Timepoints
PatientID            
0                  59
1                  59
2                  59
3                  59
4                  59
...               ...
8911               59
8912               59
8913               59
8914               59
8915               59

[8916 rows x 1 columns]

From the above, it appears that for each patient we have 60 records in this dataset. You can also see from below that $60$ divides the number of records in this dataset.

In [11]:
df.shape[0] / 60

8916.0

In [12]:
df.describe()

VL            CD4        Rel CD4         Gender  \
count  534960.000000  534960.000000  534960.000000  534960.000000   
mean      905.857731     674.120672      29.281191       1.004823   
std      4197.878019     729.376832      16.117512       0.069279   
min         0.913153      39.063290       2.622727       1.000000   
25%        16.507067     279.255997      18.198733       1.000000   
50%        54.765035     465.809700      25.571101       1.000000   
75%       209.027337     840.335037      35.715859       1.000000   
max     88600.980000   19146.166000     356.268520       2.000000   

              Ethnic  Base Drug Combo      Comp. INI    Comp. NNRTI  \
count  534960.000000    534960.000000  534960.000000  534960.000000   
mean        3.705698         0.591014       2.584576       2.371233   
std         0.457939         1.249615       0.984959       0.656057   
min         2.000000         0.000000       0.000000       0.000000   
25%         3.000000         0.000000       3.000000       2.000000   
50%         4.000000         0.000000       3.000000       2.000000   
75%         4.000000         1.000000       3.000000       3.000000   
max         4.000000         5.000000       3.000000       3.000000   

            Extra PI    Extra pk-En         VL (M)        CD4 (M)  \
count  534960.000000  534960.000000  534960.000000  534960.000000   
mean        4.688777       0.032993       0.206513       0.166125   
std         0.970413       0.178619       0.404803       0.372193   
min         0.000000       0.000000       0.000000       0.000000   
25%         5.000000       0.000000       0.000000       0.000000   
50%         5.000000       0.000000       0.000000       0.000000   
75%         5.000000       0.000000       0.000000       0.000000   
max         5.000000       1.000000       1.000000       1.000000   

            Drug (M)      PatientID     Timepoints  
count  534960.000000  534960.000000  534960.000000  
mean        0.844355    4457.500000      29.500000  
std         0.362519    2573.829889      17.318118  
min         0.000000       0.000000       0.000000  
25%         1.000000    2228.750000      14.750000  
50%         1.000000    4457.500000      29.500000  
75%         1.000000    6686.250000      44.250000  
max         1.000000    8915.000000      59.000000

In [13]:
df.columns.tolist()

['VL',
 'CD4',
 'Rel CD4',
 'Gender',
 'Ethnic',
 'Base Drug Combo',
 'Comp. INI',
 'Comp. NNRTI',
 'Extra PI',
 'Extra pk-En',
 'VL (M)',
 'CD4 (M)',
 'Drug (M)',
 'PatientID',
 'Timepoints']

In [14]:
df['Comp. NNRTI'].unique()

array([1., 3., 2., 0.])

## Q: Get some insights on the reward

Let's first take a look at the 3d plot of the loss w.r.t VLt and CD4t

In [17]:
import plotly.graph_objects as go

In [35]:
VLt_range = numpy.linspace(df.VL.min()-1, df.VL.max(), 50)
CD4t_range = numpy.linspace(df.CD4.min(), df.CD4.max(), 50)
VLt_range, CD4t_range = numpy.meshgrid(VLt_range, CD4t_range)

def reward_function(VLt, CD4t):
    VLt_inclusion_element_mask = VLt > 0
    return VLt_inclusion_element_mask * numpy.nan_to_num(
        -0.7 * numpy.log(VLt) + 0.6 * numpy.log(CD4t), 0) + (~VLt_inclusion_element_mask) * (5 + 0.6 * numpy.log(CD4t))

    
reward = reward_function(VLt_range, CD4t_range)

/tmp/ipykernel_322465/4235157043.py:8: RuntimeWarning:

invalid value encountered in log



In [37]:
reward

array([[ 7.19910989, -3.0509117 , -3.53613154, ..., -5.74604793,
        -5.76078533, -5.77521885],
       [ 8.63687997, -1.61314162, -2.09836146, ..., -4.30827785,
        -4.32301525, -4.33744877],
       [ 9.02481018, -1.22521141, -1.71043125, ..., -3.92034764,
        -3.93508504, -3.94951856],
       ...,
       [10.89096313,  0.64094154,  0.1557217 , ..., -2.05419469,
        -2.06893209, -2.08336561],
       [10.90356859,  0.653547  ,  0.16832716, ..., -2.04158923,
        -2.05632663, -2.07076015],
       [10.91591466,  0.66589307,  0.18067323, ..., -2.02924316,
        -2.04398056, -2.05841408]])

In [38]:
reward_function(numpy.array([0]), numpy.array([1]))

/tmp/ipykernel_322465/4235157043.py:8: RuntimeWarning:

divide by zero encountered in log



array([5.])

In [39]:
fig = go.Figure(data=[go.Surface(x=VLt_range, y=CD4t_range, z=reward)])

fig.update_layout(
    title="Reward function",
    scene = dict(
        xaxis_title='VLt',
        yaxis_title='CD4t',
        zaxis_title='rt'
    )
)

fig.show()

Inherently, we don't have any rows with VL being 0:

In [16]:
assert df[df.VL==0].shape[0] == 0

We know that when analyzing patient $\texttt{PID}$ and at timestep $\texttt{t}$, we have access to all features up until $\texttt{t-1}$, and all of the features OTHER THAN $\text{VL}_t$ and $\text{CD4}_t$. Our treatment recommendation would revolve around $\text{NNRTI}_t$.

Given the current dataset, the way I am proposing to approach this problem is as follows:


* We have a function $$\text{VL}_t, \text{CD4}_t, r_t \leftarrow f(\tau_t, \{v_{i}\}_{i<t}, \mathbf{\tilde{v}}_t, \{\tau_i\}_{<t}; \theta)$$

Let's say we have such a good model $f$ that this approach predicts reasonable results on the expected reward given these inputs, thus, it can be leveraged with the same data and by changing the value of $\tau_t$ from the $4$ options, and pick the recommended treatment:

$$ \tau^*_t \leftarrow \argmax_{\tau_t} f(\tau_t, \{v_{i}\}_{i<t}, \mathbf{\tilde{v}}_t, \{\tau_i\}_{<t}, d; \theta)[2] $$

In [43]:
df.describe()

VL            CD4        Rel CD4         Gender  \
count  534960.000000  534960.000000  534960.000000  534960.000000   
mean      905.857731     674.120672      29.281191       1.004823   
std      4197.878019     729.376832      16.117512       0.069279   
min         0.913153      39.063290       2.622727       1.000000   
25%        16.507067     279.255997      18.198733       1.000000   
50%        54.765035     465.809700      25.571101       1.000000   
75%       209.027337     840.335037      35.715859       1.000000   
max     88600.980000   19146.166000     356.268520       2.000000   

              Ethnic  Base Drug Combo      Comp. INI    Comp. NNRTI  \
count  534960.000000    534960.000000  534960.000000  534960.000000   
mean        3.705698         0.591014       2.584576       2.371233   
std         0.457939         1.249615       0.984959       0.656057   
min         2.000000         0.000000       0.000000       0.000000   
25%         3.000000         0.000000       3.000000       2.000000   
50%         4.000000         0.000000       3.000000       2.000000   
75%         4.000000         1.000000       3.000000       3.000000   
max         4.000000         5.000000       3.000000       3.000000   

            Extra PI    Extra pk-En         VL (M)        CD4 (M)  \
count  534960.000000  534960.000000  534960.000000  534960.000000   
mean        4.688777       0.032993       0.206513       0.166125   
std         0.970413       0.178619       0.404803       0.372193   
min         0.000000       0.000000       0.000000       0.000000   
25%         5.000000       0.000000       0.000000       0.000000   
50%         5.000000       0.000000       0.000000       0.000000   
75%         5.000000       0.000000       0.000000       0.000000   
max         5.000000       1.000000       1.000000       1.000000   

            Drug (M)      PatientID     Timepoints  
count  534960.000000  534960.000000  534960.000000  
mean        0.844355    4457.500000      29.500000  
std         0.362519    2573.829889      17.318118  
min         0.000000       0.000000       0.000000  
25%         1.000000    2228.750000      14.750000  
50%         1.000000    4457.500000      29.500000  
75%         1.000000    6686.250000      44.250000  
max         1.000000    8915.000000      59.000000

In [45]:
for k in df.columns:
    if k not in ['Timepoints', 'PatientID']:
        print(f"{k}: {df[k].unique()}")

VL: [1141.8958    134.19055    47.274055 ...   23.014017   31.049942
   18.980227]
CD4: [1070.0356   444.5419   230.53404 ... 1441.0657   424.17233  295.5861 ]
Rel CD4: [32.65416   14.7757225 15.087534  ... 33.672344  24.711374  30.766958 ]
Gender: [1. 2.]
Ethnic: [4. 3. 2.]
Base Drug Combo: [0. 1. 3. 5. 4. 2.]
Comp. INI: [3. 2. 0. 1.]
Comp. NNRTI: [1. 3. 2. 0.]
Extra PI: [5. 3. 1. 4. 2. 0.]
Extra pk-En: [0. 1.]
VL (M): [1. 0.]
CD4 (M): [1. 0.]
Drug (M): [0. 1.]


Per this, we now know what to embed and what to project.

df.groupby('PatientID').std()[
    'Extra pk-En'
]

In [48]:
df.groupby('PatientID').std()[
    'Extra pk-En'
].max()

0.5042194840896107